[package]
name = "protoc-gen-grpc-gateway"
version = "0.1.0"
edition = "2021"
description = "A protoc plugin that generates a gRPC-Gateway proxy in Rust."
license = "MIT"
repository = "https://github.com/IberoRust/grpc-gateway-rust"
keywords = ["grpc", "protobuf", "gateway", "proxy", "generator"]
categories = ["development-tools", "network-programming", "web-programming"]
readme = "../README.md"

[lib]
name = "gateway_codegen"
path = "src/lib.rs"

[dependencies]
prost = "0.14"
gateway-annotations = { version = "0.1.0", path = "../gateway-annotations" }
gateway-internal = { version = "0.1.0", path = "../gateway-internal" }

quote = "1.0"
proc-macro2 = "1.0"
heck = "0.5"
syn = { version = "2.0", features = ["full", "parsing"] }
prettyplease = "0.2"

[[bin]]
name = "protoc-gen-grpc-gateway"
path = "src/main.rs"
