[package]
name = "gateway-annotations"
version = "0.1.2"
edition = "2021"
description = "Annotations for the Rust gRPC Gateway."
license = "Apache-2.0"
repository = "https://github.com/IberoRust/grpc-gateway-rust"
keywords = ["grpc", "protobuf", "gateway", "annotations"]
categories = ["development-tools"]

[lib]
doctest = false

[dependencies]
prost = "0.14"

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"
