[package]
name = "gateway-runtime"
version = "0.2.0"
edition = "2021"
description = "Runtime library for the Rust gRPC Gateway."
license = "Apache-2.0"
repository = "https://github.com/IberoRust/grpc-gateway-rust"
keywords = ["grpc", "protobuf", "gateway", "runtime"]
categories = ["web-programming::http-server"]

[dependencies]
percent-encoding = "2.3"
gateway-internal = { version = "0.1.1", path = "../gateway-internal" }
http = "1.4"
tonic = "0.14"
prost = "0.14"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
bytes = "1.5"
tower = { version = "0.5", features = ["util"] }
http-body = "1.0"
http-body-util = "0.1"
multer = "3.1"

[features]
default = ["std", "tokio"]
std = []

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dependencies.tokio]
version = "1"
features = ["signal", "macros"]
optional = true
