//! # Forward
//!
//! ## Purpose
//! Provides utilities for constructing HTTP responses from gRPC messages. This module
//! bridges the gap between the gRPC client's output (Protobuf messages or streams) and
//! the HTTP server's response format (bytes).
//!
//! ## Scope
//! This module exposes functions to:
//! -   `forward_response_message`: Convert a single gRPC message into a unary HTTP response.
//! -   `forward_response_stream`: Convert a stream of gRPC messages into a single aggregated HTTP response.
//!
//! ## Position in the Architecture
//! These functions are called by the code generated by `gateway-codegen` at the end of
//! a request handler. They take the result from the gRPC client, encode it using the
//! specified `Codec`, and wrap it in an `http::Response`.
//!
//! ## Design Constraints
//! -   **Codec Agnostic**: Functions are generic over `Codec`, allowing them to work with any supported wire format.
//! -   **Buffered Responses**: Currently aggregates streaming responses into a single byte vector to simplify the return type.

use crate::codec::Codec;
use crate::errors::GatewayError;
use crate::{BoxBody, GatewayRequest};
use futures::{Stream, StreamExt};
use http::{Response, StatusCode};
use http_body::Frame;
use http_body_util::{BodyExt, Full, StreamBody};
use prost::Message;

/// Constructs an HTTP response from a single gRPC message.
///
/// This function encodes the message using the provided codec and builds a standard
/// HTTP 200 OK response with the appropriate `Content-Type`.
///
/// # Parameters
/// *   `codec`: The codec used to encode the message.
/// *   `msg`: The gRPC message to send.
/// *   `req`: The incoming request (used to determine `Accept` header).
///
/// # Returns
/// A `Result` containing the HTTP response with the encoded body, or a `GatewayError` if encoding fails.
pub fn forward_response_message<T: Message + serde::Serialize, C: Codec>(
    codec: &C,
    msg: &T,
    req: &GatewayRequest,
) -> Result<Response<BoxBody>, GatewayError> {
    let accept = req
        .headers()
        .get(http::header::ACCEPT)
        .and_then(|h| h.to_str().ok());
    let content_type = codec.encoder_content_type(accept);
    let body_bytes = codec.encode(msg, Some(&content_type))?;
    let body = BodyExt::boxed_unsync(Full::new(body_bytes).map_err(|never| match never {}));

    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", content_type)
        .body(body)
        .map_err(GatewayError::Http)
}

/// Constructs an HTTP response from a gRPC stream.
///
/// This function collects all items from the stream, encodes them, and aggregates them
/// into a single byte vector.
///
/// **Note**: This implementation buffers the entire stream in memory. This is a simplification
/// to ensure compatibility with `tower::Service` return types that expect a concrete body type.
///
/// # Parameters
/// *   `codec`: The codec used to encode stream items.
/// *   `stream`: The incoming gRPC stream.
/// *   `req`: The incoming request (used to determine `Accept` header).
///
/// # Returns
/// A `Result` containing the HTTP response with the aggregated body, or a `GatewayError` if processing fails.
pub async fn forward_response_stream<S, T, C>(
    codec: &C,
    stream: S,
    req: &GatewayRequest,
) -> Result<Response<BoxBody>, GatewayError>
where
    S: Stream<Item = Result<T, tonic::Status>> + Send + 'static,
    T: Message + serde::Serialize,
    C: Codec + Clone + Send + Sync + 'static,
{
    let accept = req
        .headers()
        .get(http::header::ACCEPT)
        .and_then(|h| h.to_str().ok());
    let content_type = codec.encoder_content_type(accept);
    let codec = codec.clone();
    let content_type_clone = content_type.clone();

    let stream = stream.map(move |result| match result {
        Ok(msg) => match codec.encode(&msg, Some(&content_type_clone)) {
            Ok(bytes) => Ok(Frame::data(bytes)),
            Err(e) => Err(e),
        },
        Err(e) => Err(GatewayError::Upstream(e)),
    });

    let body = BodyExt::boxed_unsync(StreamBody::new(stream));

    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", content_type)
        .body(body)
        .map_err(GatewayError::Http)
}
