//! # Forward
//!
//! ## Purpose
//! Provides utilities for constructing HTTP responses from gRPC messages. This module
//! bridges the gap between the gRPC client's output (Protobuf messages or streams) and
//! the HTTP server's response format (bytes).
//!
//! ## Scope
//! This module exposes functions to:
//! -   `forward_response_message`: Convert a single gRPC message into a unary HTTP response.
//! -   `forward_response_stream`: Convert a stream of gRPC messages into a single aggregated HTTP response.
//!
//! ## Position in the Architecture
//! These functions are called by the code generated by `gateway-codegen` at the end of
//! a request handler. They take the result from the gRPC client, encode it using the
//! specified `Codec`, and wrap it in an `http::Response`.
//!
//! ## Design Constraints
//! -   **Codec Agnostic**: Functions are generic over `Codec`, allowing them to work with any supported wire format.
//! -   **Buffered Responses**: Currently aggregates streaming responses into a single byte vector to simplify the return type.

use crate::codec::Codec;
use crate::errors::GatewayError;
use crate::{BoxBody, GatewayRequest};
use futures::{Stream, StreamExt};
use http::{Response, StatusCode};
use http_body::Frame;
use http_body_util::{BodyExt, Full, StreamBody};
use prost::Message;

/// Constructs an HTTP response from a single gRPC message.
///
/// This function encodes the message using the provided codec and builds a standard
/// HTTP 200 OK response with the appropriate `Content-Type`.
///
/// # Parameters
/// *   `codec`: The codec used to encode the message.
/// *   `msg`: The gRPC message to send.
/// *   `req`: The incoming request (used to determine `Accept` header).
///
/// # Returns
/// A `Result` containing the HTTP response with the encoded body, or a `GatewayError` if encoding fails.
pub fn forward_response_message<T: Message + serde::Serialize, C: Codec>(
    codec: &C,
    msg: &T,
    req: &GatewayRequest,
) -> Result<Response<BoxBody>, GatewayError> {
    let accept = req
        .headers()
        .get(http::header::ACCEPT)
        .and_then(|h| h.to_str().ok());
    let content_type = codec.encoder_content_type(accept);
    let body_bytes = codec.encode(msg, Some(&content_type))?;
    let body = BodyExt::boxed_unsync(Full::new(body_bytes).map_err(|never| match never {}));

    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", content_type)
        .body(body)
        .map_err(GatewayError::Http)
}

/// Constructs an HTTP response from a gRPC stream.
///
/// This function collects all items from the stream, encodes them, and aggregates them
/// into a single byte vector.
///
/// **Note**: This implementation buffers the entire stream in memory. This is a simplification
/// to ensure compatibility with `tower::Service` return types that expect a concrete body type.
///
/// # Parameters
/// *   `codec`: The codec used to encode stream items.
/// *   `stream`: The incoming gRPC stream.
/// *   `req`: The incoming request (used to determine `Accept` header).
///
/// # Returns
/// A `Result` containing the HTTP response with the aggregated body, or a `GatewayError` if processing fails.
pub async fn forward_response_stream<S, T, C>(
    codec: &C,
    stream: S,
    req: &GatewayRequest,
) -> Result<Response<BoxBody>, GatewayError>
where
    S: Stream<Item = Result<T, tonic::Status>> + Send + 'static,
    T: Message + serde::Serialize,
    C: Codec + Clone + Send + Sync + 'static,
{
    let accept = req
        .headers()
        .get(http::header::ACCEPT)
        .and_then(|h| h.to_str().ok());
    let content_type = codec.encoder_content_type(accept);
    let codec = codec.clone();
    let content_type_clone = content_type.clone();

    let stream = stream.map(move |result| match result {
        Ok(msg) => match codec.encode(&msg, Some(&content_type_clone)) {
            Ok(bytes) => Ok(Frame::data(bytes)),
            Err(e) => Err(e),
        },
        Err(e) => Err(GatewayError::Upstream(e)),
    });

    let body = BodyExt::boxed_unsync(StreamBody::new(stream));

    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", content_type)
        .body(body)
        .map_err(GatewayError::Http)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Mock Codec
    #[derive(Clone)]
    struct MockCodec;
    impl Codec for MockCodec {
        fn encode<T: Message + serde::Serialize>(
            &self,
            _item: &T,
            _buf: Option<&str>,
        ) -> Result<crate::bytes::Bytes, GatewayError> {
            Ok(crate::bytes::Bytes::from_static(b"ok"))
        }
        fn decode<T: Message + Default + serde::de::DeserializeOwned>(
            &self,
            _buf: &[u8],
            _content_type: Option<&str>,
        ) -> Result<T, GatewayError> {
            unimplemented!()
        }
        fn encoder_content_type(&self, _accept: Option<&str>) -> String {
            "text/plain".to_string()
        }
    }

    #[derive(serde::Serialize, prost::Message)]
    struct Dummy {
        #[prost(string, tag = "1")]
        foo: String,
    }

    #[test]
    fn test_forward_response_message() {
        let codec = MockCodec;
        let msg = Dummy::default();
        let req = http::Request::builder().body(Vec::new()).unwrap();

        let resp = forward_response_message(&codec, &msg, &req).unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(resp.headers().get("content-type").unwrap(), "text/plain");
        // body check skipped
    }

    #[tokio::test]
    async fn test_forward_response_stream() {
        let codec = MockCodec;
        let stream = futures::stream::iter(vec![Ok(Dummy::default())]);
        let req = http::Request::builder().body(Vec::new()).unwrap();

        let resp = forward_response_stream(&codec, stream, &req).await.unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(resp.headers().get("content-type").unwrap(), "text/plain");
    }

    #[test]
    fn test_forward_response_message_accept() {
        let codec = MockCodec; // returns text/plain regardless, but we check arg passed.
                               // MockCodec ignores accept.
                               // But function logic: req -> accept header -> codec.encoder_content_type(accept).
                               // So it passes it.
        let req = http::Request::builder()
            .header("accept", "application/json")
            .body(Vec::new())
            .unwrap();
        let resp = forward_response_message(&codec, &Dummy::default(), &req).unwrap();
        assert_eq!(resp.headers().get("content-type").unwrap(), "text/plain");
    }

    #[tokio::test]
    async fn test_forward_response_stream_error() {
        let codec = MockCodec;
        let stream = futures::stream::iter(vec![Err::<Dummy, tonic::Status>(
            tonic::Status::internal("fail"),
        )]);
        let req = http::Request::builder().body(Vec::new()).unwrap();

        // forward_response_stream maps stream items to Result<Frame, Error>.
        // StreamBody iterates. If item is error, body stream yields error.
        // It does NOT return Err from function immediately unless setup fails.
        // The function returns Result<Response...>.
        // The body is StreamBody.
        // The stream inside yields Result.

        let resp = forward_response_stream(&codec, stream, &req).await.unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        // To verify body error, we must collect body.
        let body = resp.into_body();
        let collected = body.collect().await;
        // Should be error?
        // stream yields Err(GatewayError::Upstream(status)).
        assert!(collected.is_err());
    }
}
