//! # Gateway Runtime
//!
//! ## Overview
//! The `gateway-runtime` crate provides the essential runtime components for the `grpc-gateway-rust` ecosystem.
//! It acts as the bridge between HTTP/JSON requests and gRPC services, handling routing, transcoding,
//! authentication, and middleware orchestration.
//!
//! ## Core Components
//!
//! *   **[Gateway]**: The primary builder and entry point. It orchestrates the middleware stack and constructs
//!     the final `tower::Service` responsible for handling requests.
//! *   **[Router]**: Manages the registration and matching of gRPC service methods to HTTP paths.
//! *   **[Codec]**: Handles the transcoding between HTTP body formats (JSON) and Protocol Buffers.
//! *   **[errors::GatewayError]**: The canonical error type for the gateway, mapping gRPC status codes to HTTP responses.
//!
//! ## Middleware Architecture
//! The gateway uses `tower::Service` layers to compose functionality. The execution order for an incoming request is:
//! 1.  **Tracing/Metrics**: Telemetry recording.
//! 2.  **Error Handling**: Catches internal or upstream errors and formats them (e.g., as JSON).
//! 3.  **Response Modification**: Late-stage modification of HTTP responses.
//! 4.  **Header Processing**: Filtering and renaming of incoming/outgoing headers.
//! 5.  **Metadata Extraction**: Converting headers or context into gRPC metadata.
//! 6.  **Routing & Auth**: Matching the path and verifying authentication requirements.
//! 7.  **Dispatch**: Invoking the generated service handler.
//!
//! ## Feature Flags
//! *   `std` (default): Enables standard library features (e.g., `std::error::Error` for `GatewayError`).
//!     Disable this for `no_std` environments (requires `alloc`).
//!
//! ## Integration
//! This crate is typically used by code generated by `protoc-gen-grpc-gateway-rust`, but can also be used
//! manually to build custom gateways.

#![doc(html_root_url = "https://docs.rs/grpc-gateway-rust/0.2.0")]

// Re-export the alloc crate for use within derived code.
#[doc(hidden)]
pub extern crate alloc;

pub mod codec;
pub mod defaults;
pub mod errors;
pub mod forward;
pub mod gateway;
pub mod handlers;
pub mod layers;
pub mod metadata;
#[doc(hidden)]
pub mod pattern;
pub mod router;
pub mod shutdown;
pub mod utilities;

// Public dependencies re-exported for convenience in generated code.
pub use bytes;
pub use http;
pub use http_body;
pub use http_body_util;
pub use tonic;
pub use tower;

use alloc::vec::Vec;

// Primary public API
pub use codec::Codec;
pub use errors::GatewayError;
pub use gateway::{Gateway, UnescapingMode};
pub use router::Router;

/// A boxed body that implements `http_body::Body`.
///
/// Used as the standard response body type for the gateway to ensure type erasure and compatibility.
pub type BoxBody = http_body_util::combinators::UnsyncBoxBody<bytes::Bytes, GatewayError>;

/// A generic HTTP request body for the gateway.
///
/// The gateway currently buffers the request body into `Vec<u8>` to support
/// multiple reads during transcoding or inspection.
pub type GatewayRequest = http::Request<Vec<u8>>;

/// A generic HTTP response body for the gateway.
pub type GatewayResponse = http::Response<BoxBody>;

/// A generic Result type for gateway operations.
pub type GatewayResult = Result<GatewayResponse, GatewayError>;

/// A boxed cloneable service for handling gateway requests.
///
/// This is the type returned by `Gateway::into_service()` and expected by generated code registries.
pub type BoxedGatewayService =
    tower::util::BoxCloneService<http::Request<Vec<u8>>, http::Response<BoxBody>, GatewayError>;
