//! # Gateway Runtime
//!
//! ## Purpose
//! This module provides the runtime support library for the gRPC Gateway. It contains the
//! essential components required by the generated code to bridge HTTP/JSON requests to
//! gRPC services. This includes routing logic, message serialization/deserialization (transcoding),
//! metadata translation, and error handling.
//!
//! ## Scope
//! This module is responsible for:
//! -   **Routing**: Matching incoming HTTP requests to registered gRPC service methods using the `Router`.
//! -   **Transcoding**: Converting between HTTP body formats (e.g., JSON) and Protocol Buffers using the `Codec` trait.
//! -   **Forwarding**: Translating HTTP headers to gRPC metadata and invoking the underlying gRPC client.
//! -   **Error Handling**: Mapping gRPC status codes to appropriate HTTP status codes and response bodies.
//!
//! ## Position in the Architecture
//! The `gateway-runtime` crate serves as the foundation for the code generated by `gateway-codegen`.
//! Generated service registrations import and utilize the types and functions defined here.
//! It acts as the middleware layer between the HTTP server (e.g., `hyper`) and the gRPC client (e.g., `tonic`).
//!
//! ## Design Constraints
//! -   **`no_std` Support**: The library is designed to support `no_std` environments by relying on the `alloc` crate
//!     and conditionally compiling `std`-dependent features.
//! -   **Type Safety**: It leverages Rust's type system to ensure correct mapping between HTTP and gRPC types.
//! -   **Extensibility**: The `Codec` and `Router` abstractions allow for plugging in different serialization formats and routing strategies.

#![doc(html_root_url = "https://docs.rs/grpc-gateway-rust/0.1.1")]

// Re-export the alloc crate for use within derived code.
#[doc(hidden)]
pub extern crate alloc;

pub mod codec;
pub mod errors;
pub mod forward;
pub mod metadata;
pub mod pattern;
pub mod router;
pub mod utilities;

pub use bytes;
pub use http;
pub use http_body;
pub use http_body_util;
pub use tonic;
pub use tower;

use alloc::vec::Vec;
use errors::GatewayError;

/// A boxed body that implements `http_body::Body`.
pub type BoxBody = http_body_util::combinators::UnsyncBoxBody<bytes::Bytes, GatewayError>;

/// A generic HTTP request body for the gateway.
pub type GatewayRequest = http::Request<Vec<u8>>;

/// A generic HTTP response body for the gateway.
pub type GatewayResponse = http::Response<BoxBody>;

/// A generic Result type for gateway operations.
pub type GatewayResult = Result<GatewayResponse, GatewayError>;

/// A boxed cloneable service for handling gateway requests.
pub type BoxedGatewayService =
    tower::util::BoxCloneService<http::Request<Vec<u8>>, http::Response<BoxBody>, GatewayError>;
